const CATEGORIES = [
  { id: "daily", name: "Günlük Hayat & Sosyal İletişim", icon: "🗣️", totalItems: 500, totalSets: 25, description: "Günlük konuşmalarda sık kullanılan kelime ve kalıplar" },
  { id: "business", name: "İş Dünyası & Profesyonel İletişim", icon: "👔", totalItems: 400, totalSets: 20, description: "İş hayatında kullanılan profesyonel ifadeler" },
  { id: "finance", name: "Finans, Ekonomi & Yatırım", icon: "💰", totalItems: 300, totalSets: 15, description: "Finans ve ekonomi terimleri" },
  { id: "connectors", name: "Cümle İskeletleri & Bağlaçlar", icon: "🔗", totalItems: 300, totalSets: 15, description: "Cümle yapıları ve bağlaç kalıpları" },
  { id: "analytical", name: "Analitik & Mantıksal Çıkarım", icon: "📊", totalItems: 200, totalSets: 10, description: "Analitik düşünme ve mantıksal ifadeler" },
  { id: "travel", name: "Seyahat & Rutinler", icon: "✈️", totalItems: 200, totalSets: 10, description: "Seyahat ve günlük rutin ifadeleri" },
  { id: "idioms", name: "Popüler Deyimler / Idioms", icon: "🎭", totalItems: 100, totalSets: 5, description: "Yaygın İngilizce deyimler ve atasözleri" }
];

const FLASHCARD_DATA = [
  // Category: daily (Set 1)
  {
    id: 1,
    category: "daily",
    deck: 1,
    target_expression: "Make a decision",
    key_word: "Decision (Karar)",
    type: "chunk",
    pronunciation: "/meɪk ə dɪˈsɪʒ.ən/",
    turkish_meaning: "Karar vermek",
    example_en: "I need to make a decision quickly.",
    example_tr: "Hızlıca bir karar vermem gerekiyor."
  },
  {
    id: 2,
    category: "daily",
    deck: 1,
    target_expression: "Keep in mind",
    key_word: "Mind (Akıl/Zihin)",
    type: "chunk",
    pronunciation: "/kiːp ɪn maɪnd/",
    turkish_meaning: "Aklında bulundurmak",
    example_en: "Keep in mind that it might rain tomorrow.",
    example_tr: "Yarın yağmur yağabileceğini aklında bulundur."
  },
  {
    id: 3,
    category: "daily",
    deck: 1,
    target_expression: "Take a break",
    key_word: "Break (Mola)",
    type: "chunk",
    pronunciation: "/teɪk ə breɪk/",
    turkish_meaning: "Mola vermek",
    example_en: "Let's take a break and get some coffee.",
    example_tr: "Hadi biraz mola verip kahve alalım."
  },
  {
    id: 4,
    category: "daily",
    deck: 1,
    target_expression: "Get along with",
    key_word: "Along (Beraber)",
    type: "chunk",
    pronunciation: "/ɡet əˈlɒŋ wɪð/",
    turkish_meaning: "Biriyle iyi geçinmek",
    example_en: "I get along with my coworkers very well.",
    example_tr: "İş arkadaşlarımla çok iyi geçinirim."
  },
  {
    id: 5,
    category: "daily",
    deck: 1,
    target_expression: "Figure out",
    key_word: "Figure (Şekil/Rakam)",
    type: "chunk",
    pronunciation: "/ˈfɪɡ.ər aʊt/",
    turkish_meaning: "Anlamak, çözmek",
    example_en: "We need to figure out what went wrong.",
    example_tr: "Neyin yanlış gittiğini çözmemiz lazım."
  },
  {
    id: 6,
    category: "daily",
    deck: 1,
    target_expression: "Come up with",
    key_word: "Come (Gelmek)",
    type: "chunk",
    pronunciation: "/kʌm ʌp wɪð/",
    turkish_meaning: "Bir fikir veya plan bulmak, üretmek",
    example_en: "She came up with a great idea for the project.",
    example_tr: "Proje için harika bir fikir buldu."
  },
  {
    id: 7,
    category: "daily",
    deck: 1,
    target_expression: "Deal with",
    key_word: "Deal (Anlaşma)",
    type: "chunk",
    pronunciation: "/diːl wɪð/",
    turkish_meaning: "Başa çıkmak, ilgilenmek",
    example_en: "I have a lot of emails to deal with today.",
    example_tr: "Bugün ilgilenmem gereken bir sürü e-posta var."
  },
  {
    id: 8,
    category: "daily",
    deck: 1,
    target_expression: "Run into",
    key_word: "Run (Koşmak)",
    type: "chunk",
    pronunciation: "/rʌn ˈɪn.tuː/",
    turkish_meaning: "Tesadüfen karşılaşmak",
    example_en: "I ran into an old friend at the supermarket.",
    example_tr: "Süpermarkette eski bir arkadaşımla karşılaştım."
  },
  {
    id: 9,
    category: "daily",
    deck: 1,
    target_expression: "Look forward to",
    key_word: "Forward (İleri)",
    type: "chunk",
    pronunciation: "/lʊk ˈfɔː.wəd tuː/",
    turkish_meaning: "Dört gözle beklemek",
    example_en: "I am looking forward to seeing you again.",
    example_tr: "Seni tekrar görmeyi dört gözle bekliyorum."
  },
  {
    id: 10,
    category: "daily",
    deck: 1,
    target_expression: "Give up",
    key_word: "Give (Vermek)",
    type: "chunk",
    pronunciation: "/ɡɪv ʌp/",
    turkish_meaning: "Pes etmek, bırakmak",
    example_en: "Don't give up on your dreams.",
    example_tr: "Hayallerinden asla vazgeçme."
  },
  {
    id: 11,
    category: "daily",
    deck: 1,
    target_expression: "Put off",
    key_word: "Put (Koymak)",
    type: "chunk",
    pronunciation: "/pʊt ɒf/",
    turkish_meaning: "Ertelemek",
    example_en: "We had to put off the meeting until tomorrow.",
    example_tr: "Toplantıyı yarına ertelemek zorunda kaldık."
  },
  {
    id: 12,
    category: "daily",
    deck: 1,
    target_expression: "Bring up",
    key_word: "Bring (Getirmek)",
    type: "chunk",
    pronunciation: "/brɪŋ ʌp/",
    turkish_meaning: "Konuyu açmak, gündeme getirmek",
    example_en: "Why did you bring up that topic again?",
    example_tr: "O konuyu neden tekrar açtın?"
  },
  {
    id: 13,
    category: "daily",
    deck: 1,
    target_expression: "Turn out",
    key_word: "Turn (Dönmek)",
    type: "chunk",
    pronunciation: "/tɜːn aʊt/",
    turkish_meaning: "Sonuçlanmak, ortaya çıkmak",
    example_en: "The movie turned out to be really good.",
    example_tr: "Film gerçekten iyi çıktı."
  },
  {
    id: 14,
    category: "daily",
    deck: 1,
    target_expression: "End up",
    key_word: "End (Son)",
    type: "chunk",
    pronunciation: "/end ʌp/",
    turkish_meaning: "Sonunda bir durumda/yerde bulmak (kendini)",
    example_en: "We got lost and ended up in a strange neighborhood.",
    example_tr: "Kaybolduk ve sonunda yabancı bir mahallede bulduk kendimizi."
  },
  {
    id: 15,
    category: "daily",
    deck: 1,
    target_expression: "Point out",
    key_word: "Point (Nokta)",
    type: "chunk",
    pronunciation: "/pɔɪnt aʊt/",
    turkish_meaning: "İşaret etmek, belirtmek",
    example_en: "She pointed out a mistake in the report.",
    example_tr: "Rapordaki bir hatayı belirtti."
  },
  {
    id: 16,
    category: "daily",
    deck: 1,
    target_expression: "Set up",
    key_word: "Set (Ayar)",
    type: "chunk",
    pronunciation: "/set ʌp/",
    turkish_meaning: "Kurmak, düzenlemek",
    example_en: "I need to set up my new computer.",
    example_tr: "Yeni bilgisayarımı kurmam gerekiyor."
  },
  {
    id: 17,
    category: "daily",
    deck: 1,
    target_expression: "Pick up",
    key_word: "Pick (Seçmek)",
    type: "chunk",
    pronunciation: "/pɪk ʌp/",
    turkish_meaning: "Almak (birini/bir şeyi)",
    example_en: "Can you pick me up from the airport?",
    example_tr: "Beni havaalanından alabilir misin?"
  },
  {
    id: 18,
    category: "daily",
    deck: 1,
    target_expression: "Carry on",
    key_word: "Carry (Taşımak)",
    type: "chunk",
    pronunciation: "/ˈkær.i ɒn/",
    turkish_meaning: "Devam etmek",
    example_en: "Please carry on with your work.",
    example_tr: "Lütfen işinize devam edin."
  },
  {
    id: 19,
    category: "daily",
    deck: 1,
    target_expression: "Sort out",
    key_word: "Sort (Tür/Sıralamak)",
    type: "chunk",
    pronunciation: "/sɔːt aʊt/",
    turkish_meaning: "Çözmek, halletmek, ayırmak",
    example_en: "We need to sort out this problem soon.",
    example_tr: "Bu problemi yakında halletmemiz gerekiyor."
  },
  {
    id: 20,
    category: "daily",
    deck: 1,
    target_expression: "Work out",
    key_word: "Work (İş/Çalışmak)",
    type: "chunk",
    pronunciation: "/wɜːk aʊt/",
    turkish_meaning: "Antrenman yapmak, işe yaramak/çözmek",
    example_en: "Everything will work out in the end.",
    example_tr: "Sonunda her şey yoluna girecek."
  },

  // Category: business (Set 1)
  {
    id: 21,
    category: "business",
    deck: 1,
    target_expression: "Meet a deadline",
    key_word: "Deadline (Son tarih)",
    type: "chunk",
    pronunciation: "/miːt ə ˈded.laɪn/",
    turkish_meaning: "Bir işi zamanında (son teslim tarihine kadar) yetiştirmek",
    example_en: "We have to work late tonight to meet the deadline.",
    example_tr: "İşi zamanında yetiştirmek için bu gece geç saate kadar çalışmalıyız."
  },
  {
    id: 22,
    category: "business",
    deck: 1,
    target_expression: "Close a deal",
    key_word: "Deal (Anlaşma)",
    type: "chunk",
    pronunciation: "/kləʊz ə diːl/",
    turkish_meaning: "Bir anlaşmayı sonuçlandırmak",
    example_en: "The sales team managed to close a major deal yesterday.",
    example_tr: "Satış ekibi dün büyük bir anlaşmayı kapatmayı başardı."
  },
  {
    id: 23,
    category: "business",
    deck: 1,
    target_expression: "Reach an agreement",
    key_word: "Agreement (Anlaşma)",
    type: "chunk",
    pronunciation: "/riːtʃ ən əˈɡriː.mənt/",
    turkish_meaning: "Anlaşmaya varmak",
    example_en: "After hours of discussion, we finally reached an agreement.",
    example_tr: "Saatler süren tartışmanın ardından nihayet bir anlaşmaya vardık."
  },
  {
    id: 24,
    category: "business",
    deck: 1,
    target_expression: "Submit a proposal",
    key_word: "Proposal (Teklif)",
    type: "chunk",
    pronunciation: "/səbˈmɪt ə prəˈpəʊ.zəl/",
    turkish_meaning: "Bir teklif sunmak",
    example_en: "Please submit your proposal by Friday at the latest.",
    example_tr: "Lütfen teklifinizi en geç Cuma gününe kadar sunun."
  },
  {
    id: 25,
    category: "business",
    deck: 1,
    target_expression: "Attend a meeting",
    key_word: "Attend (Katılmak)",
    type: "chunk",
    pronunciation: "/əˈtend ə ˈmiː.tɪŋ/",
    turkish_meaning: "Toplantıya katılmak",
    example_en: "I cannot take this call, I need to attend a meeting now.",
    example_tr: "Bu aramayı açamam, şu an bir toplantıya katılmam gerek."
  },
  {
    id: 26,
    category: "business",
    deck: 1,
    target_expression: "Follow up",
    key_word: "Follow (Takip etmek)",
    type: "chunk",
    pronunciation: "/ˈfɒl.əʊ ʌp/",
    turkish_meaning: "Takip etmek (bir konunun/işin peşine düşmek)",
    example_en: "I will follow up with the client next week.",
    example_tr: "Gelecek hafta müşteri ile konuyu takip edeceğim."
  },
  {
    id: 27,
    category: "business",
    deck: 1,
    target_expression: "Take charge of",
    key_word: "Charge (Sorumluluk)",
    type: "chunk",
    pronunciation: "/teɪk tʃɑːdʒ ɒv/",
    turkish_meaning: "Sorumluluğunu üstlenmek",
    example_en: "She will take charge of the marketing department.",
    example_tr: "Pazarlama departmanının sorumluluğunu o üstlenecek."
  },
  {
    id: 28,
    category: "business",
    deck: 1,
    target_expression: "Draw up a contract",
    key_word: "Contract (Sözleşme)",
    type: "chunk",
    pronunciation: "/drɔː ʌp ə ˈkɒn.trækt/",
    turkish_meaning: "Sözleşme hazırlamak",
    example_en: "The lawyers are drawing up a new contract.",
    example_tr: "Avukatlar yeni bir sözleşme hazırlıyorlar."
  },
  {
    id: 29,
    category: "business",
    deck: 1,
    target_expression: "Launch a product",
    key_word: "Launch (Piyasaya sürmek)",
    type: "chunk",
    pronunciation: "/lɔːntʃ ə ˈprɒd.ʌkt/",
    turkish_meaning: "Bir ürünü piyasaya sürmek",
    example_en: "We are planning to launch a new product in the spring.",
    example_tr: "İlkbaharda yeni bir ürün piyasaya sürmeyi planlıyoruz."
  },
  {
    id: 30,
    category: "business",
    deck: 1,
    target_expression: "Cut costs",
    key_word: "Cost (Maliyet)",
    type: "chunk",
    pronunciation: "/kʌt kɒsts/",
    turkish_meaning: "Maliyetleri kısmak",
    example_en: "The company needs to cut costs to survive this year.",
    example_tr: "Şirketin bu yıl hayatta kalabilmesi için maliyetleri kısması gerekiyor."
  },
  {
    id: 31,
    category: "business",
    deck: 1,
    target_expression: "Boost revenue",
    key_word: "Revenue (Gelir)",
    type: "chunk",
    pronunciation: "/buːst ˈrev.ən.juː/",
    turkish_meaning: "Geliri artırmak",
    example_en: "Our new advertising campaign helped boost revenue.",
    example_tr: "Yeni reklam kampanyamız gelirimizi artırmaya yardımcı oldu."
  },
  {
    id: 32,
    category: "business",
    deck: 1,
    target_expression: "Handle a complaint",
    key_word: "Complaint (Şikayet)",
    type: "chunk",
    pronunciation: "/ˈhæn.dəl ə kəmˈpleɪnt/",
    turkish_meaning: "Bir şikayetle ilgilenmek",
    example_en: "She knows how to handle a customer complaint gracefully.",
    example_tr: "Müşteri şikayetiyle nazikçe nasıl ilgileneceğini biliyor."
  },
  {
    id: 33,
    category: "business",
    deck: 1,
    target_expression: "Delegate tasks",
    key_word: "Delegate (Devretmek)",
    type: "chunk",
    pronunciation: "/ˈdel.ɪ.ɡeɪt tɑːsks/",
    turkish_meaning: "Görevleri devretmek",
    example_en: "A good manager knows how to delegate tasks effectively.",
    example_tr: "İyi bir yönetici görevleri etkili bir şekilde nasıl devredeceğini bilir."
  },
  {
    id: 34,
    category: "business",
    deck: 1,
    target_expression: "Set priorities",
    key_word: "Priority (Öncelik)",
    type: "chunk",
    pronunciation: "/set praɪˈɒr.ə.tiz/",
    turkish_meaning: "Öncelikleri belirlemek",
    example_en: "We must set clear priorities for the next quarter.",
    example_tr: "Gelecek çeyrek için net öncelikler belirlemeliyiz."
  },
  {
    id: 35,
    category: "business",
    deck: 1,
    target_expression: "Go over the budget",
    key_word: "Budget (Bütçe)",
    type: "chunk",
    pronunciation: "/ɡəʊ ˈəʊ.vər ðə ˈbʌdʒ.ɪt/",
    turkish_meaning: "Bütçeyi gözden geçirmek (veya bütçeyi aşmak)",
    example_en: "Let's go over the budget before we finalize the plan.",
    example_tr: "Planı sonlandırmadan önce bütçeyi gözden geçirelim."
  },
  {
    id: 36,
    category: "business",
    deck: 1,
    target_expression: "Break even",
    key_word: "Even (Eşit)",
    type: "chunk",
    pronunciation: "/breɪk ˈiː.vən/",
    turkish_meaning: "Başa baş noktasına gelmek (ne kar ne zarar)",
    example_en: "The business finally managed to break even this month.",
    example_tr: "İşletme nihayet bu ay başa baş noktasına gelmeyi başardı."
  },
  {
    id: 37,
    category: "business",
    deck: 1,
    target_expression: "Scale up",
    key_word: "Scale (Ölçek)",
    type: "chunk",
    pronunciation: "/skeɪl ʌp/",
    turkish_meaning: "Büyütmek, ölçeği artırmak",
    example_en: "We need more investment to scale up our operations.",
    example_tr: "Operasyonlarımızı büyütmek için daha fazla yatırıma ihtiyacımız var."
  },
  {
    id: 38,
    category: "business",
    deck: 1,
    target_expression: "Step down",
    key_word: "Step (Adım)",
    type: "chunk",
    pronunciation: "/step daʊn/",
    turkish_meaning: "İstifa etmek, görevi bırakmak",
    example_en: "The CEO decided to step down due to health reasons.",
    example_tr: "CEO, sağlık sebepleriyle görevden ayrılmaya karar verdi."
  },
  {
    id: 39,
    category: "business",
    deck: 1,
    target_expression: "Take over",
    key_word: "Over (Üzerinde/Fazla)",
    type: "chunk",
    pronunciation: "/teɪk ˈəʊ.vər/",
    turkish_meaning: "Devralmak, yönetimi ele almak",
    example_en: "The new manager will take over starting next week.",
    example_tr: "Yeni yönetici gelecek haftadan itibaren görevi devralacak."
  },
  {
    id: 40,
    category: "business",
    deck: 1,
    target_expression: "Lay off",
    key_word: "Lay (Koymak)",
    type: "chunk",
    pronunciation: "/leɪ ɒf/",
    turkish_meaning: "İşten çıkarmak",
    example_en: "They had to lay off a hundred workers during the crisis.",
    example_tr: "Kriz sırasında yüz işçiyi işten çıkarmak zorunda kaldılar."
  },

  // Category: idioms (Set 1)
  {
    id: 41,
    category: "idioms",
    deck: 1,
    target_expression: "Break the ice",
    key_word: "Ice (Buz)",
    type: "chunk",
    pronunciation: "/breɪk ði aɪs/",
    turkish_meaning: "Buzları kırmak, ortalığı yumuşatmak",
    example_en: "He told a joke to break the ice at the start of the meeting.",
    example_tr: "Toplantının başında buzları kırmak için bir espri yaptı."
  },
  {
    id: 42,
    category: "idioms",
    deck: 1,
    target_expression: "Hit the nail on the head",
    key_word: "Nail (Çivi)",
    type: "chunk",
    pronunciation: "/hɪt ðə neɪl ɒn ðə hed/",
    turkish_meaning: "Tam üstüne basmak, taşı gediğine koymak",
    example_en: "You hit the nail on the head with that comment.",
    example_tr: "O yorumunla tam üstüne bastın."
  },
  {
    id: 43,
    category: "idioms",
    deck: 1,
    target_expression: "Bite the bullet",
    key_word: "Bullet (Mermi)",
    type: "chunk",
    pronunciation: "/baɪt ðə ˈbʊl.ɪt/",
    turkish_meaning: "Zor bir duruma katlanmak, dişini sıkmak",
    example_en: "I hate going to the dentist, but I'll just have to bite the bullet.",
    example_tr: "Dişçiye gitmekten nefret ediyorum ama dişimi sıkmak zorundayım."
  },
  {
    id: 44,
    category: "idioms",
    deck: 1,
    target_expression: "A piece of cake",
    key_word: "Cake (Kek/Pasta)",
    type: "chunk",
    pronunciation: "/ə piːs əv keɪk/",
    turkish_meaning: "Çocuk oyuncağı, çok kolay",
    example_en: "Don't worry about the exam; it will be a piece of cake.",
    example_tr: "Sınav için endişelenme; çocuk oyuncağı olacak."
  },
  {
    id: 45,
    category: "idioms",
    deck: 1,
    target_expression: "Break a leg",
    key_word: "Leg (Bacak)",
    type: "chunk",
    pronunciation: "/breɪk ə leɡ/",
    turkish_meaning: "İyi şanslar (genellikle sahneye çıkanlara söylenir)",
    example_en: "You'll do great in the play tonight. Break a leg!",
    example_tr: "Bu akşamki oyunda harika olacaksın. İyi şanslar!"
  },
  {
    id: 46,
    category: "idioms",
    deck: 1,
    target_expression: "Once in a blue moon",
    key_word: "Moon (Ay)",
    type: "chunk",
    pronunciation: "/wʌns ɪn ə bluː muːn/",
    turkish_meaning: "Kırk yılda bir, çok nadir",
    example_en: "I only eat junk food once in a blue moon.",
    example_tr: "Kırk yılda bir abur cubur yerim."
  },
  {
    id: 47,
    category: "idioms",
    deck: 1,
    target_expression: "The ball is in your court",
    key_word: "Court (Kort/Saha)",
    type: "chunk",
    pronunciation: "/ðə bɔːl ɪz ɪn jɔː kɔːt/",
    turkish_meaning: "Top sende, sıra sende (karar senin)",
    example_en: "I made my offer, so now the ball is in your court.",
    example_tr: "Teklifimi yaptım, yani şimdi top sende."
  },
  {
    id: 48,
    category: "idioms",
    deck: 1,
    target_expression: "Burn the midnight oil",
    key_word: "Oil (Yağ)",
    type: "chunk",
    pronunciation: "/bɜːn ðə ˈmɪd.naɪt ɔɪl/",
    turkish_meaning: "Gece geç saatlere kadar çalışmak",
    example_en: "She's been burning the midnight oil to finish her thesis.",
    example_tr: "Tezini bitirmek için gece geç saatlere kadar çalışıyor."
  },
  {
    id: 49,
    category: "idioms",
    deck: 1,
    target_expression: "Cost an arm and a leg",
    key_word: "Cost (Maliyet)",
    type: "chunk",
    pronunciation: "/kɒst ən ɑːm ænd ə leɡ/",
    turkish_meaning: "Çok pahalıya mal olmak",
    example_en: "This sports car is beautiful, but it costs an arm and a leg.",
    example_tr: "Bu spor araba çok güzel ama aşırı pahalı."
  },
  {
    id: 50,
    category: "idioms",
    deck: 1,
    target_expression: "Cut to the chase",
    key_word: "Chase (Kovalamaca)",
    type: "chunk",
    pronunciation: "/kʌt tuː ðə tʃeɪs/",
    turkish_meaning: "Sadede gelmek, asıl meseleye geçmek",
    example_en: "We don't have much time, so let's cut to the chase.",
    example_tr: "Pek vaktimiz yok, o yüzden sadede gelelim."
  },
  {
    id: 51,
    category: "idioms",
    deck: 1,
    target_expression: "Get out of hand",
    key_word: "Hand (El)",
    type: "chunk",
    pronunciation: "/ɡet aʊt əv hænd/",
    turkish_meaning: "Kontrolden çıkmak",
    example_en: "The party got out of hand when uninvited guests arrived.",
    example_tr: "Davetsiz misafirler gelince parti kontrolden çıktı."
  },
  {
    id: 52,
    category: "idioms",
    deck: 1,
    target_expression: "Go the extra mile",
    key_word: "Mile (Mil)",
    type: "chunk",
    pronunciation: "/ɡəʊ ði ˈek.strə maɪl/",
    turkish_meaning: "Gerektiğinden fazlasını yapmak, ekstra çaba göstermek",
    example_en: "He is always willing to go the extra mile for his clients.",
    example_tr: "Müşterileri için her zaman ekstra çaba göstermeye isteklidir."
  },
  {
    id: 53,
    category: "idioms",
    deck: 1,
    target_expression: "In the same boat",
    key_word: "Boat (Tekne)",
    type: "chunk",
    pronunciation: "/ɪn ðə seɪm bəʊt/",
    turkish_meaning: "Aynı gemide olmak (aynı zor durumda olmak)",
    example_en: "We all lost our jobs, so we are in the same boat.",
    example_tr: "Hepimiz işimizi kaybettik, yani aynı gemideyiz."
  },
  {
    id: 54,
    category: "idioms",
    deck: 1,
    target_expression: "It takes two to tango",
    key_word: "Tango (Tango)",
    type: "chunk",
    pronunciation: "/ɪt teɪks tuː tuː ˈtæŋ.ɡəʊ/",
    turkish_meaning: "İki tarafın da suçu/katılımı var",
    example_en: "She blames him for the divorce, but it takes two to tango.",
    example_tr: "Boşanma için onu suçluyor ama bu işler iki kişiliktir."
  },
  {
    id: 55,
    category: "idioms",
    deck: 1,
    target_expression: "Let the cat out of the bag",
    key_word: "Cat (Kedi)",
    type: "chunk",
    pronunciation: "/let ðə kæt aʊt əv ðə bæɡ/",
    turkish_meaning: "Sırrı ağzından kaçırmak",
    example_en: "I accidentally let the cat out of the bag about the surprise party.",
    example_tr: "Sürpriz parti hakkındaki sırrı yanlışlıkla ağzımdan kaçırdım."
  },
  {
    id: 56,
    category: "idioms",
    deck: 1,
    target_expression: "Miss the boat",
    key_word: "Boat (Tekne)",
    type: "chunk",
    pronunciation: "/mɪs ðə bəʊt/",
    turkish_meaning: "Fırsatı kaçırmak",
    example_en: "If you don't buy the tickets now, you'll miss the boat.",
    example_tr: "Biletleri şimdi almazsan fırsatı kaçırırsın."
  },
  {
    id: 57,
    category: "idioms",
    deck: 1,
    target_expression: "On the same page",
    key_word: "Page (Sayfa)",
    type: "chunk",
    pronunciation: "/ɒn ðə seɪm peɪdʒ/",
    turkish_meaning: "Aynı fikirde olmak, aynı noktada olmak",
    example_en: "Before we sign the contract, let's make sure we are on the same page.",
    example_tr: "Sözleşmeyi imzalamadan önce aynı fikirde olduğumuzdan emin olalım."
  },
  {
    id: 58,
    category: "idioms",
    deck: 1,
    target_expression: "Pull someone's leg",
    key_word: "Leg (Bacak)",
    type: "chunk",
    pronunciation: "/pʊl ˈsʌm.wʌnz leɡ/",
    turkish_meaning: "Biriyle dalga geçmek, işletmek",
    example_en: "Are you serious, or are you just pulling my leg?",
    example_tr: "Ciddi misin, yoksa beni mi işletiyorsun?"
  },
  {
    id: 59,
    category: "idioms",
    deck: 1,
    target_expression: "The last straw",
    key_word: "Straw (Saman/Pipet)",
    type: "chunk",
    pronunciation: "/ðə lɑːst strɔː/",
    turkish_meaning: "Bardağı taşıran son damla",
    example_en: "When he showed up late again, it was the last straw.",
    example_tr: "Yine geç geldiğinde, bu bardağı taşıran son damlaydı."
  },
  {
    id: 60,
    category: "idioms",
    deck: 1,
    target_expression: "Under the weather",
    key_word: "Weather (Hava)",
    type: "chunk",
    pronunciation: "/ˈʌn.də ðə ˈweð.ər/",
    turkish_meaning: "Kendini biraz hasta/kötü hissetmek",
    example_en: "I'm feeling a bit under the weather today, so I won't go to work.",
    example_tr: "Bugün biraz hasta hissediyorum, o yüzden işe gitmeyeceğim."
  }
];

// ============================================
// ŞABLON: Yeni kart eklemek için aşağıdaki yapıyı kopyalayın
// ============================================
// {
//   id: NEXT_ID,
//   category: "daily|business|finance|connectors|analytical|travel|idioms",
//   deck: SET_NUMBER,
//   target_expression: "English Expression",
//   key_word: "Keyword (Türkçe)",
//   type: "word|chunk",
//   pronunciation: "/IPA pronunciation/",
//   turkish_meaning: "Türkçe anlam",
//   example_en: "English example sentence.",
//   example_tr: "Türkçe çeviri."
// },
